#自动生成数据库表（关键）
spring:
  #关闭Thymeleaf的缓存
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # 激活 prod
  profiles:
    active: pro
# 也可以同时激活多个 profile
# spring.profiles.active: prod,proddb,prodlog
# dev 配置
#spring:
#  profiles: pro

# 图片上传地址
upload:
  file:
    path: /home/publish/html/img

api:
  appId: wx98c69df355fad828 # 小程序ID
  Appsecret: 15d180b368829741c05cb31476e68b5d
  mchID: 1628655062 # 商户号
  v2Key: FLKtRVXq75okuzRnzXFh2by00FdBSma5 # APIv2密钥
  notifyUrl: https://api.xinhang618.com/wx/pay/notify # 支付成功后的回调地址，域名下来后换成域名