server:
  port: 8090
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait:  -1
        min-idle: 0
    timeout: 100000
  datasource:
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    validationQuery: select 'x'
    initialSize: 1
    maxWait: 60000
    poolPreparedStatements: true
    #    filters: stat
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 20
    username: root
    url: jdbc:mysql://localhost:3306/hangxin618?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&useAffectedRows=true&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&useSSL=false
    password: XinHang220618
#    url: jdbc:mysql://localhost:3306/pg_220421?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&useAffectedRows=true&rewriteBatchedStatements=true
#    password: test223
#    password: JxB9TzsqsOG7IxWqNiRoMG5PsZx3PG4mdxI+4Efk+tneUThYyzyRboCOU7stRYkwGs9yDT54Gpp68S2T7MIKJQ==
    type: com.alibaba.druid.pool.DruidDataSource
#    publickey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJjqQ6qWrFGQi4Uk+UWNw4MnzRSxWW8J3cdl1H3Jgskm926FxzzvGTsj2DzQLzxZv2s4T3knFmeRxOgIKMeLFikCAwEAAQ==
    druid:
      filter:
        config:
          enabled: true
#      connection-properties: config.decrypt=true;config.decrypt.key=${spring.datasource.publickey}
    testOnBorrow: false
    maxOpenPreparedStatements: 20
    testWhileIdle: true
    minEvictableIdleTimeMillis: 300000
    timeBetweenEvictionRunsMillis: 60000
    testOnReturn: false
    name: test
  servlet:
    multipart:
      max-request-size: 1800MB
      max-file-size: 300MB
logging:
  config: classpath:logback-spring.xml
api:
  certPath: /home/publish/cert/apiclient_cert.p12