server:
  port: 8090
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    timeout: 100000
  datasource:
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    validationQuery: select 'x'
    initialSize: 1
    maxWait: 60000
    poolPreparedStatements: true
    #    filters: stat
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 20
    username: root
    url: jdbc:mysql://39.101.203.127:3306/hangxin618?serverTimezone=GMT%2B8&useUnicode=true&amp;characterEncoding=utf-8&useSSL=false&useAffectedRows=true&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&useSSL=false
    #    url: jdbc:mysql://rm-bp1ukh6tc93ip5nn13o.mysql.rds.aliyuncs.com:3306/hangxin0618?serverTimezone=GMT%2B8&useUnicode=true&amp;characterEncoding=utf-8&useSSL=false&useAffectedRows=true&rewriteBatchedStatements=true
    password: XinHang220618
    #    password: test223
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filter:
        config:
          enabled: true
    #      connection-properties: config.decrypt=true;config.decrypt.key=${spring.datasource.publickey}
    testOnBorrow: false
    maxOpenPreparedStatements: 20
    testWhileIdle: true
    minEvictableIdleTimeMillis: 300000
    timeBetweenEvictionRunsMillis: 60000
    testOnReturn: false
    name: test
  servlet:
    multipart:
      max-request-size: 1800MB
      max-file-size: 300MB
logging:
  config: classpath:logback-local-spring.xml
  level:
    com:
      berryproduct:
        modules:
          wes:
            mapper: debug

api:
  certPath: D:\Program Files\Downloads\WXCertUtil\cert\1628655062_20220717_cert
